"use client";

import { useState } from "react";
import { usePredictions } from "@/hooks/usePredictions";
import { RiskBadge } from "@/components/ui/RiskBadge";
import Skeleton from "@/components/ui/Skeleton";
import EmptyState from "@/components/dashboard/EmptyState";
import { Lightbulb, ChevronDown, ChevronUp, Brain, Clock } from "lucide-react";

export default function StudentSuggestionsPage() {
    const { latestPrediction, history, loading } = usePredictions();
    const [expandedId, setExpandedId] = useState<string | null>(null);

    if (loading) {
        return (
            <div className="flex flex-col gap-8 pb-10">
                <div className="flex flex-col gap-2">
                    <Skeleton className="h-8 w-64" />
                    <Skeleton className="h-5 w-96" />
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Skeleton className="h-80 rounded-xl" />
                    <Skeleton className="h-80 rounded-xl" />
                </div>
            </div>
        );
    }

    // Reverse history for display (newest first)
    const pastPredictions = history.slice(0, -1).length > 0
        ? [...history].reverse().slice(1)
        : [];

    return (
        <div className="flex flex-col gap-8 pb-10">
            <div className="flex flex-col gap-2">
                <h1 className="text-3xl font-bold text-text-primary tracking-tight">AI Insights & Suggestions</h1>
                <p className="text-text-secondary">Review personalized recommendations generated by PRISM&apos;s AI models.</p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
                {/* Latest Suggestion - Prominent */}
                <div className="lg:col-span-3 bg-bg-secondary border border-accent/30 rounded-xl relative overflow-hidden p-6">
                    <div className="absolute inset-0 bg-accent opacity-[0.02]" />

                    <div className="relative z-10">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="w-10 h-10 rounded-xl bg-accent/10 flex items-center justify-center">
                                <Lightbulb size={20} className="text-accent" />
                            </div>
                            <div>
                                <h3 className="font-semibold text-text-primary">Latest AI Recommendations</h3>
                                {latestPrediction && (
                                    <p className="text-xs text-text-muted">
                                        Generated {latestPrediction.timestamp?.toDate?.()?.toLocaleDateString("en-US", {
                                            month: "long",
                                            day: "numeric",
                                            year: "numeric",
                                        })}
                                    </p>
                                )}
                            </div>
                            {latestPrediction && (
                                <div className="ml-auto">
                                    <RiskBadge variant={(latestPrediction.riskLevel || "Low").toLowerCase() as any} className="capitalize">
                                        {latestPrediction.riskLevel}
                                    </RiskBadge>
                                </div>
                            )}
                        </div>

                        {latestPrediction?.suggestions && latestPrediction.suggestions.length > 0 ? (
                            <>
                                <ul className="space-y-4 mb-6">
                                    {latestPrediction.suggestions.map((s, i) => (
                                        <li
                                            key={i}
                                            className="flex items-start gap-3 p-3 bg-bg-primary border border-border-primary rounded-lg"
                                        >
                                            <span className="mt-0.5 w-6 h-6 rounded-full bg-accent/10 text-accent flex items-center justify-center text-xs font-bold shrink-0">
                                                {i + 1}
                                            </span>
                                            <p className="text-sm text-text-secondary leading-relaxed">{s}</p>
                                        </li>
                                    ))}
                                </ul>

                                {latestPrediction.explanation && (
                                    <div className="pt-4 border-t border-border-primary">
                                        <div className="flex items-center gap-2 mb-2">
                                            <Brain size={14} className="text-text-muted" />
                                            <span className="text-xs font-medium text-text-muted uppercase tracking-wider">AI Explainability</span>
                                        </div>
                                        <p className="text-sm text-text-secondary leading-relaxed">
                                            {latestPrediction.explanation}
                                        </p>
                                    </div>
                                )}

                                {/* Prediction Metrics */}
                                <div className="grid grid-cols-3 gap-3 mt-6">
                                    <div className="bg-bg-primary border border-border-primary rounded-lg p-3 text-center">
                                        <p className="text-xs text-text-muted mb-1">Stress</p>
                                        <p className="text-lg font-mono font-bold text-text-primary">
                                            {Math.round((latestPrediction.predictionData?.stressLevel ?? latestPrediction.riskScore ?? 0) * 100)}%
                                        </p>
                                    </div>
                                    <div className="bg-bg-primary border border-border-primary rounded-lg p-3 text-center">
                                        <p className="text-xs text-text-muted mb-1">Failure Risk</p>
                                        <p className="text-lg font-mono font-bold text-text-primary">
                                            {Math.round((latestPrediction.predictionData?.failureProbability ?? 0) * 100)}%
                                        </p>
                                    </div>
                                    <div className="bg-bg-primary border border-border-primary rounded-lg p-3 text-center">
                                        <p className="text-xs text-text-muted mb-1">Attendance Risk</p>
                                        <p className="text-lg font-mono font-bold text-text-primary">
                                            {Math.round((latestPrediction.predictionData?.attendanceDecline ?? 0) * 100)}%
                                        </p>
                                    </div>
                                </div>
                            </>
                        ) : (
                            <EmptyState
                                title="No suggestions available"
                                description="Submit daily logs to receive personalized AI suggestions."
                            />
                        )}
                    </div>
                </div>

                {/* Past Suggestions */}
                <div className="lg:col-span-2 bg-bg-secondary border border-border-primary rounded-xl p-6">
                    <div className="flex items-center gap-2 mb-4">
                        <Clock size={16} className="text-text-muted" />
                        <h3 className="font-semibold text-text-primary">Suggestion History</h3>
                    </div>

                    {pastPredictions.length > 0 ? (
                        <div className="space-y-3 max-h-[600px] overflow-y-auto pr-1">
                            {pastPredictions.map((pred) => {
                                const id = pred.id ?? pred.timestamp?.toDate?.()?.toISOString() ?? "";
                                const isExpanded = expandedId === id;

                                return (
                                    <div
                                        key={id}
                                        className="border border-border-primary rounded-lg overflow-hidden bg-bg-primary"
                                    >
                                        <button
                                            onClick={() => setExpandedId(isExpanded ? null : id)}
                                            className="w-full flex items-center justify-between p-3 hover:bg-bg-hover transition-colors"
                                        >
                                            <div className="flex items-center gap-2">
                                                <RiskBadge
                                                    variant={(pred.riskLevel || "Low").toLowerCase() as any}
                                                    className="capitalize text-[10px] px-1.5 py-0"
                                                >
                                                    {pred.riskLevel}
                                                </RiskBadge>
                                                <span className="text-sm text-text-primary">
                                                    {pred.timestamp?.toDate?.()?.toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                                                </span>
                                            </div>
                                            {isExpanded ? <ChevronUp size={14} className="text-text-muted" /> : <ChevronDown size={14} className="text-text-muted" />}
                                        </button>

                                        {isExpanded && (
                                            <div className="px-3 pb-3 border-t border-border-primary pt-3">
                                                {pred.suggestions?.map((s, i) => (
                                                    <p key={i} className="text-xs text-text-secondary mb-2 flex items-start gap-2">
                                                        <span className="text-accent mt-0.5">•</span>
                                                        {s}
                                                    </p>
                                                ))}
                                                {pred.explanation && (
                                                    <p className="text-xs text-text-muted mt-2 italic">{pred.explanation}</p>
                                                )}
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    ) : (
                        <div className="flex items-center justify-center py-16 text-sm text-text-muted">
                            No past suggestions yet.
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
