export default function StudentSuggestionsPage() {
    return (
        <div className="flex flex-col gap-8 pb-10">
            <div className="flex flex-col gap-2">
                <h1 className="text-3xl font-bold text-text-primary tracking-tight">AI Insights & Suggestions</h1>
                <p className="text-text-secondary">Review personalized recommendations generated by PRISM's AI models.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="min-h-64 bg-bg-secondary border border-accent border-opacity-30 rounded-xl relative overflow-hidden flex items-center justify-center p-6">
                    <div className="absolute inset-0 bg-accent opacity-[0.02]" />
                    <p className="text-accent relative z-10">Latest AI Suggestion</p>
                </div>

                <div className="min-h-64 bg-bg-secondary border border-border-primary rounded-xl flex items-center justify-center p-6">
                    <p className="text-text-muted">Past Suggestions History</p>
                </div>
            </div>
        </div>
    );
}
